### ISSUE TITLE
你好.弹幕多条时的显示.

### ISSUE THREAD

**Issue by shanglina** [chenqihui/QHDanumuDemo#1]
你好,当弹幕有多条时,比如一秒有30条弹幕,该怎么设置弹幕 durationTime  现在的情况是飞的特别快,几乎看不到

**Comment by runningSoul** [comment]
你好，你怎么发到我邮箱了，弹幕你可以自己写一个，思路不难，这个弹幕是不是.a的

发自 网易邮箱大师
在2016年03月16日 22:00，shanglina 写道:

你好,当弹幕有多条时,比如一秒有30条弹幕,该怎么设置弹幕 durationTime 现在的情况是飞的特别快,几乎看不到

**Comment by shanglina** [comment]
你好,打扰了,我现在的情况是 数据是从 socket 过来的,来一条就给弹幕系统一条, 这个 demo 是 一次给了好多条,这块我应该怎么处理呢?  打扰了

**Comment by runningSoul** [comment]
这个我也没看过，我一会回去跟你看看，你们推过来会不会一次推多条？你加我qq503313857

发自这个网易邮箱大师
在2016年03月16日 22:07，shanglina 写道:

你好,打扰了,我现在的情况是 数据是从 socket 过来的,来一条就给弹幕系统一条, 这个 demo 是 一次给了好多条,这块我应该怎么处理呢? 打扰了

**Comment by chenqihui** [comment]
你看看
@property (nonatomic) NSUInteger durationTime;//添加弹幕的间隔时间
这个属性

我demo那个发送就是一条一条来的

还有为啥会到你邮件呢？？你那邮箱是？
